app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from . import views
from posts.views import tag_post_list
from posts import apis as posts_apis
from members import apis as members_apis

urlpatterns_api_posts = ([
    path('post/', posts_apis.PostList.as_view(), name='post-list'),
    path('post/<int:pk>/', posts_apis.PostDetail.as_view(), name='post-detail'),
    path('post/<int:post_pk>/like/', posts_apis.PostLikeCreateDestroy.as_view(), name='post-like'),

    path('postlike/', posts_apis.PostLikeCreateAPIView.as_view()),
    path('postlike/<int:pk>/', posts_apis.PostLikeDestroyAPIView.as_view()),
], 'posts')

urlpatterns_api_members = ([
    path('auth-token/', members_apis.AuthTokenView.as_view()),
    path('user/profile/', members_apis.UserDetail.as_view()),
    path('user/<int:pk>/', members_apis.UserDetail.as_view()),
    path('user/view/profile/', members_apis.UserDetailAPIView.as_view()),
    path('user/view/<int:pk>/', members_apis.UserDetailAPIView.as_view()),
], 'members')

urlpatterns_api = ([
    path('posts/', include(urlpatterns_api_posts)),
    path('members/', include(urlpatterns_api_members)),
], 'api')

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.index, name='index'),

    path('', RedirectView.as_view(pattern_name='posts:post-list'), name='index'),
    # /posts/로 들어오는 URL은 posts.urls모듈에서 처리
    path('posts/', include('posts.urls')),
    path('explore/tags/<str:tag_name>/',
         tag_post_list,
         name='tag-post-list'),
    path('members/', include('members.urls')),

    path('api/', include(urlpatterns_api)),
]
# MEDIA_URL로 시작하는 URL은 static()내의 serve() 함수를 통해 처리
# MEDIA_ROOT기준으로 파일을 검색함
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/members/urls.py
from django.urls import path

from . import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('facebook-login/', views.facebook_login, name='facebook-login'),
]

app/posts/urls.py
from django.urls import path

from . import views, apis

# 이 urls모듈의 app_name에 'posts'를 사용
# reverse또는 템플릿의 {% url %}태그에서 사용
app_name = 'posts'

urlpatterns = [
    # posts.urls내의 패턴들은, prefix가 '/posts/'임
    path('',
         views.post_list,
         name='post-list'),
    path('create/',
         views.post_create,
         name='post-create'),
    path('<int:post_pk>/comments/create/',
         views.comment_create,
         name='comment-create'),
    path('tag-search/',
         views.tag_search,
         name='tag-search'),
    path('<int:post_pk>/like-toggle/',
         views.post_like_toggle,
         name='post-like-toggle'),

    path('api/tag-search/',
         apis.tag_search,
         name='api-tag-search'),
]

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<!-- Normalize.css: 브라우저마다 다른 CSS기본 설정값들을 같게 맞춰줌 -->
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<!-- jQuery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<title>Instagram</title>
	<style>
		.square {
		}
		.square:before {
			content: '';
			padding: 50% 0;
			display: inline-block;
		}
		.square > .thumbnail {
			display: block;
			width: 100%;
			background-size: cover;
			background-position: center center;
		}
		.messages-container {
			position: fixed;
			top: 10px;
			left: 10px;
			width: 300px;
		}
		#search-form {
			position: relative;
			overflow: visible;
		}
		ul.search-list {
			position: absolute;
			display: none;
			width: 100%;
			height: 200px;
			overflow-y: scroll;
			top: 100%;
			left: 0;
			background-color: white;
			border: 1px solid #999;
			border-radius: 5px;
			z-index: 999;
			list-style-type: none;
			padding: 0;
			margin: 0;
		}
		ul.search-list > li {
			display: block;
			border-bottom: 1px solid #999;
			padding: 8px;
		}
		ul.search-list > li > a {
			color: #666;
		}
	</style>
</head>
<body>
	<div id="wrap">
		<!--네비게이션 바-->
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<!--좌측 제목-->
			<a href="{% url 'posts:post-list' %}" class="navbar-brand">Instagram</a>
			<!--검색 form-->
			<form id="search-form" action="{% url 'posts:tag-search' %}" class="form-inline ml-md-auto">
				<input id="search-input"
							 type="text"
				       name="search_keyword"
				       class="form-control"
				       autocomplete="off"
				       placeholder="검색">
				<ul class="search-list">
				</ul>
			</form>

			<!--우측 3개 메뉴 버튼-->
			<ul class="navbar-nav ml-md-auto">
				<li class="nav-item mr-sm-1">
					<a href="{% url 'posts:post-create' %}"
					   class="btn btn-outline-primary">+ Add Post</a>
				</li>
				<li class="nav-item mr-sm-1">
					<a href="#" class="btn btn-outline-secondary">Explore</a>
				</li>
				<li class="nav-item mr-sm-1">
					<a href="#" class="btn btn-outline-secondary">Favorites</a>
				</li>
				<li class="nav-item mr-sm-1">
					<a href="{% url 'members:profile' %}" class="btn btn-outline-secondary">
						Profile
						<!-- 로그인 한 경우에만 username표시 -->
						{% if user.is_authenticated %}
							({{ user.username }})
						{% endif %}
					</a>
				</li>
				<!-- 로그인 되어있으면 로그아웃버튼, 아니면 로그인/회원가입 버튼 표시 -->
				{% if user.is_authenticated %}
				<li class="nav-item">
					<form action="{% url 'members:logout' %}"
					      method="POST">
						{% csrf_token %}
						<button type="submit"
					          class="btn btn-outline-secondary">Logout</button>
					</form>
				</li>
				{% else %}
				<li class="nav-item mr-sm-1">
					<a href="{% url 'members:login' %}"
					   class="btn btn-outline-secondary">Login</a>
				</li>
				<li class="nav-item">
					<a href="{% url 'members:signup' %}"
					   class="btn btn-outline-secondary">Signup</a>
				</li>
				{% endif %}
			</ul>

		</nav>

		<div class="container-fluid mt-3">
			{% block content %}
			{% endblock %}
		</div>

		{% if messages %}
			<div class="messages-container">
				{% for message in messages %}
					<div class="alert alert-{{ message.tags }}">
						{{ message }}
					</div>
				{% endfor %}
			</div>
		{% endif %}
	</div>
	<script>
		// 검색창 밑의 결과 창 요소
		var searchList = $('ul.search-list');

		// 검색창에서 이벤트(keyup)가 일어나면 뒤의 function을 실행함
		$('#search-input').keyup(function (e) {
			// 검색창에 입력된 값을 위 이벤트가 실행된 순간 가져옴
			var content = $('#search-input').val();

			// 만약 검색창에 있는 값의 길이가 0이면 결과창을 숨김
			if (content.length == 0) {
				searchList.hide();
			} else {
				searchList.show();
			}

			// API에 요청
			// /posts/api/tag-search/에 GET요청
			// data에 keyword로 검색창에 입력되었던 값을 보냄
			//  -> GET Parameter로 알아서 번역
			$.ajax({
				method: 'GET',
				url: 'http://localhost:8000/posts/api/tag-search/',
				data: {
					keyword: content
				}
			})
			// 요청이 성공했을 경우
			.done(function (response) {
				// response에 Tag객체의 리스트가 전달됨
				var tags = response;
				console.log(tags);
				// 검색 결과창을 비우고
				searchList.empty();
				// Tag객체 리스트를 순회
				for (var i = 0; i < response.length; i++) {
					// 현재 순회중인 객체를 index(i)를 사용해 직접 꺼냄
					var curTag = response[i];
					// 결과창에 직접 HTML요소를 삽입
					searchList.append('<li><a href="/explore/tags/' + curTag.name +'/">' + curTag.name + '<a></li>');
				}
			});
		});
	</script>
</body>
</html>